### PR TITLE
Add support for KEYS command

### PR DESCRIPTION
**Pull request by zanona**
Use [`keys`](http://redis.io/commands/KEYS) method in order to return list of keys defined by a pattern such as `key/foo/*` or `key/*`. bigcompany/hook.io#220

### CODE REVIEW

**Comment by Marak** [comment]
@zanona - A few considerations here:

Is it possible to escape upwards of the generated string based on bad user-input to `key` variable? I think not? We should double check that since we are doing it in a few places.

`keys` is not great for performance, as it could return a really large amount of results. Since we have a cap on user stored datastore documents this should be okay...but it's still not really acceptable.

Check out the documentation: http://redis.io/commands/keys

> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

Can we switch this to use SCAN with a max document limit? I believe we already have similar functionality already built in with `Datastore.recent`. Probably could build off that.

https://github.com/bigcompany/hook.io-datastore/blob/master/index.js#L33

**Comment by zanona** [comment]
Hi @Marak, thanks for your considerations. I think they are completely valid.
In fact, it's great that you have noticed this since I am all in favour to use performant solutions as much as possible. The only problem is that I am completely clueless about Redis having not experience with it at all so far.
So perhaps in this instance I may leave this up to you since I am sure you will come with a much better solution. Is that ok?

I had an initial look at SCAN and it seems that we can achieve the same which is great.
The idea is just making it easier to listing a set of resources created by a specific user for example. I appreciate the scope and structure of Redis and realised it's simply a key store datastore, but if we could as this feature to make users lives a bit easier it would be great.

I will close this PR for the moment and look forward to see SCAN implemented as per your suggestion.
Have a great day.

**Comment by Marak** [comment]
If you look at `Datastore.recent`, you will see we pretty much have the command available.

It's all there minus a few cursor configurations.

Should be relatively easy to add.

**Comment by zanona** [comment]
That's awesome! It makes sense indeed 👍

**Comment by zanona** [comment]
Sorry to pollute this thread with additional questions, but I am not sure it's necessary to create an issue for that.

I have noticed that https://hook.io/datastore/get?key=foo is accessible publicly as well as changing data https://hook.io/datastore/set?key=foo&value=baz. I know you mentioned that security would be soon implemented into the datastore, but was just wondering if this would still be the case for private hooks? — Can their respective data also be listed publicly?

**Comment by Marak** [comment]
You are probably using `anonymous` root if you are not logged into web app with session.

If you are having session, you should be only seeing your data. It should all be keyed and protected based on API key and sessions.

All URLs on hook.io site should be fully qualified API endpoints with Role Check.

**Comment by Marak** [comment]
Future security changes are related to data encryption and server configurations, not really node.js application code.

**Comment by zanona** [comment]
Weird, because I can see keys that I had created within the hook through `hook.datastore.set` publicly on the interwebs.

**Comment by Marak** [comment]
Yeah? Are you certain? Can you curl and get the same results?

It's possible there is a bug, or that it's actually already been resolved last month and not deployed.

The test suite should cover this pretty well. Check out: https://github.com/bigcompany/hook.io-test/blob/master/tests/client/datastore-api-test.js

Will need to push an update soon. We have a lot of fixes already done and pending.

**Comment by Marak** [comment]
We do have a pretty large pending delta for refactoring the datastore.

https://github.com/bigcompany/hook.io/commit/09cd65a0891e99ad18097ecf776d17559c57a476

Deploying that should make the datastore work a lot better.

**Comment by zanona** [comment]
You are probably right! I may have created those within the hook but while using hot-code gateway :) which would make sense. Silly me.
Sorry about that @Marak

**Comment by Marak** [comment]
It's okay.

The important thing is that all scenarios for `datastore` and role checks have passing tests in `master`.

Once we get some time, I'll setup a CI for the live site which will show up the passing tests.

:-)

**Pull request closed without merging**
